### ISSUE TITLE
Course Plan and Mentee Monitoring WEEK1

### ISSUE THREAD

**Issue by akshatha-k** [akshatha-k/GirlScriptManipal_Winter2019#1]
**Task Priority** : HIGH

**Task Description**
Please create your respective branches and your README.md will be the course plan. If you've already created your own github repositories then please merge it with this one.

**Person assigned**: All mentors

## Note: 
You can watch one of the Learn Git in X minutes videos and recommend them to your mentee as well. 
**If** Git is absolutely inconceivable then jump to the PS part

## Must Do's
- [ ] Create your branch on this repo or make a merge request it if you've already made one. Naming format - <domain-name> eg: ReinforcementLearning or WebDevDjango
- [ ] Course Plan ( Either make it in markdown on your respective branch or look at the 'PS:')
- [ ] Create an Issue on your respective branch with a check list comprising of the tasks you've listed in the course plan for the first week
- [ ] Explain the issue template along with how to reference issues during task commits/ upload to your mentee . Ask them to upload all of their tasks in their respective folders in your branch ( or a sub-branch , up to you )
- [ ] Assign your mentees to your weekly issues and encourage them to comment on the issue as and when they face difficulties or to create their own issues for major bugs
- [ ] Please assign me and Arpith to all your weekly task issues ( akshatha-k ) 

**PS**: Worst case -  if you absolutely detest Git then create a word document with your mentee tracking and keep uploading it to your branch every now and then . 

**PPS** : Worst Worst case - Just comment to this issue in this format and you're good to go. You can stay away from Github

1. Domain Name:
2. Course 
3. Mentee tracking google gocs/ sheet link:

**Comment by akshatha-k** [comment]
**Example:**
 I will not be using Github

> Domain Name: Opthalmology
> Course Plan link: www.blablaboo.com
> Mentee tracking document link : www.blablablabla.com
